name: CI/CD Pipeline

on:
  push:
    branches: "main"

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Docker build
      run: docker build -t "nginx404" .
    
    - name: Docker run
      run: docker run -d -p 5000:5000 nginx404
